server:
  port: 9002
logging:
  config: null
spring:
  check:
    server-uri: http://127.0.0.1:9000
  extract:
    schema: testtest
    databaseType: OG
    query-dop: 8
    debezium-enable: false
    debezium-topic: null
    debezium-groupId: null
    debezium-time-period: 1
    debezium-num-period: 1000
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    druid:
      dataSourceOne:
        driver-class-name: org.opengauss.Driver
        url: jdbc:opengauss://192.168.0.219:40300/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: test
        password: Sample@123
        initialSize: 5
        minIdle: 10
        maxActive: 20
